### ISSUE TITLE
Unable to use package with ESM rollup configuration

### ISSUE THREAD

**Issue by tirithen** [jleeson/rollup-plugin-html-literals#1]
When trying to use this package with a rollup ESM configuration (npx rollup -c rollup.config.mjs) the import of the plugin seem to fail as the transpiled code in the npm package uses the legacy module.exports syntax.

The config I use in rollup.config.mjs is:
```javascript
import resolve from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';
import minifyHTML from 'rollup-plugin-minify-html-literals';
import commonjs from '@rollup/plugin-commonjs';
import litcss from 'rollup-plugin-lit-css';

const config = {
  input: 'src/index.js',
  output: {
    file: 'dist/bundle.js',
    format: 'esm',
    sourcemap: false,
  },
  plugins: [
    commonjs(),
    minifyHTML(),
    resolve(),
    litcss(),
  ],
  preserveEntrySignatures: true,
  inlineDynamicImports: true,
};

if (process.env.NODE_ENV !== 'development') {
  config.plugins.push(terser());
}

export default config;
```

The crash I get is:
```bash
$ npx rollup -c rollup.config.mjs

[!] TypeError: minifyHTML is not a function
TypeError: minifyHTML is not a function
    at file:///home/user/project/rollup.config.mjs:16:5
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at loadConfigFile (/home/user/project/node_modules/rollup/dist/shared/loadConfigFile.js:514:16)
    at Object.loadAndParseConfigFile (/home/user/project/node_modules/rollup/dist/shared/loadConfigFile.js:491:21)
    at getConfigs (/home/user/project/node_modules/rollup/dist/bin/rollup:1753:39)
    at runRollup (/home/user/project/node_modules/rollup/dist/bin/rollup:1727:43)

```

As the source code in this repo is already using modern ESM syntax, is this possible to change in the build config for this package to ease the usage?

In case it is related to how the minify-html-literals repo builds their code, I created an issue there as well https://github.com/asyncLiz/minify-html-literals/issues/40.

The reason why it needs to be ESM is that there are other ESM rollup plugins needed in the project I work with.

**Comment by jleeson** [comment]
We are shipping a modern ESM bundle as well as a legacy CJS bundle. This may be an issue with the minify-html-literals dependency not shipping an ESM bundle to be consumed. When I have time I will do some experimentation and see what I can do to get this working for you.

**Comment by AliMD** [comment]
any temporary solution?!

**Comment by alimd** [comment]
Same issue!

This is work for me as a temporary solution

`minifyHTML.default()`

**Comment by jleeson** [comment]
@tirithen im now realizing that in your code example you are using a different rollup plugin that the one this repo is for. Your using `rollup-plugin-minify-html-literals`, while this package is `rollup-plugin-html-literals`. this package does ship an esm bundle, for it to work it just needs to work with the node runtime as its currently only setup for bundlers.

@AliMD are you also using `rollup-plugin-minify-html-literals`? With this package your temporary solution seems to throw the same error.

I will be pushing an update today that should enable usage inside a module.

**Comment by jleeson** [comment]
The latest version has support for being used in modules now. (rollup-plugin-html-literals@1.1.5)

**Comment by alimd** [comment]
@jleeson Im so sorry, I found this issue from google and just check @tirithen codes, yes we are using `rollup-plugin-minify-html-literals` not yours!

**Comment by jleeson** [comment]
no worries, you both still outlined a problem with this plugin that i was able to resolve. If the other plugin is not working, this one should work in its place.

**Comment by tirithen** [comment]
Thanks for the help either way, now we have a good candidate with ESM support :)

**Comment by alimd** [comment]
Thanks, Could you please make a comparison between these two plugins features in the readme file for better introduction?

**Comment by jleeson** [comment]
@AliMD this plugin is designed to be a drop in replacement with rollup-plugin-minify-html-literals. The main difference is now the ESM support and this plugin supports rollup 2 while last i checked the other plugin does not. I will update the readme outlining the differences.
