### ISSUE TITLE
Rollup 4.x

### ISSUE THREAD

**Issue by eskan** [jleeson/rollup-plugin-html-literals#3]
Hi,
this plugin doesn't seems to be compliant with rollup 4.x.
Regards,
Cyrille.

**Comment by jleeson** [comment]
Thanks for creating this issue @eskan. I checked the migration guide and this plugin is compatible. I updated the peerDependency requirements to not flag the unsupported version in v1.1.8 of this plugin.

**Comment by eskan** [comment]
thanks @jleeson .. so fast ;)
